title: "Pawe≈Ç Lewulis"
description: "Math, quant stuff, and other distractions."
theme: minima
markdown: kramdown

kramdown:
  math_engine: null
  input: GFM
  hard_wrap: false
  parse_block_html: true

